/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTablesRouteImport } from './routes/admin/tables'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/confirm-email'
    | '/login'
    | '/menu'
    | '/order-confirmation'
    | '/profile'
    | '/reservation'
    | '/signup'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/admin/users'
    | '/demo/tanstack-query'
    | '/orders/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confirm-email'
    | '/login'
    | '/menu'
    | '/order-confirmation'
    | '/profile'
    | '/reservation'
    | '/signup'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/admin/users'
    | '/demo/tanstack-query'
    | '/orders/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/confirm-email'
    | '/login'
    | '/menu'
    | '/order-confirmation'
    | '/profile'
    | '/reservation'
    | '/signup'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/reservations'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/admin/users'
    | '/demo/tanstack-query'
    | '/orders/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ProfileRoute: typeof ProfileRoute
  ReservationRoute: typeof ReservationRoute
  SignupRoute: typeof SignupRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ProfileRoute: ProfileRoute,
  ReservationRoute: ReservationRoute,
  SignupRoute: SignupRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
